name: C/C++ CI

on:
  push:
    branches: [ 3.7 ]
  pull_request:
    branches: [ 3.7 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: >
        sudo apt-get update &&
        sudo apt-get install -y dpkg-dev gcc g++ git make libbz2-dev libssl-dev &&
        sudo apt-get install -y liblmdb-dev libmcpp-dev
      
    - name: make
      run: OPTIMIZE=yes make CONFIGS=cpp11-shared V=1
      
  test:
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: cd cpp; python allTests.py
